In [1]:
import numpy as np

In [2]:
myarr = np.array([[2,3,878,7]], np.int64)

In [3]:
myarr

array([[  2,   3, 878,   7]], dtype=int64)

In [4]:
myarr[0, 1]

3

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0, 1] = 45

In [8]:
myarr

array([[  2,  45, 878,   7]], dtype=int64)

# Array creation: Conversion from other python structures

In [9]:
listarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({23, 23, 54})

array({54, 23}, dtype=object)

In [15]:
zeros = np.zeros((2,4))

In [16]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 4)

In [19]:
zeros.size

8

In [20]:
rng = np.arange(11)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
lspace = np.linspace(1, 5, 4)

In [23]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
emp = np.empty((2,6))       # make given size array with random number

In [25]:
emp

array([[1.12263358e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 1.11260619e-306, 3.76231868e+174],
       [6.87250053e-091, 1.10592090e-046, 1.52475813e-052,
        1.10678453e-046, 3.99910963e+252, 5.82471487e+257]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like  # make same size array 

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr = np.arange(30)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
arr.reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
arr = arr.reshape(3, 10)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
arr = arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr.shape

(30,)

In [40]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.sum(axis=0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [45]:
ar.T   # transpose of a matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

36

In [51]:
one = np.array([23, 45,1, 54])

In [52]:
one.argmax()

3

In [53]:
one.argmin()

2

In [54]:
one.argsort()

array([2, 0, 1, 3], dtype=int64)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar[2, 1] = 0

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [58]:
ar.argmin()

7

In [59]:
ar.argmax()

8

In [60]:
ar.argmin(axis=0)

array([0, 2, 0], dtype=int64)

In [61]:
ar.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [62]:
ar.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [63]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [64]:
ar.argsort(axis=0)

array([[0, 2, 0],
       [1, 0, 1],
       [2, 1, 2]], dtype=int64)

In [65]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [66]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 0, 9])

In [67]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [0],
       [9]])

In [68]:
ar.reshape((9, ))

array([1, 2, 3, 4, 5, 6, 7, 0, 9])

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [70]:
ar2 = np.array([[0, 8, 2],
       [3, 9, 2],
       [1, 7, 5]])

In [71]:
ar2

array([[0, 8, 2],
       [3, 9, 2],
       [1, 7, 5]])

In [72]:
ar + ar2

array([[ 1, 10,  5],
       [ 7, 14,  8],
       [ 8,  7, 14]])

In [73]:
ar * ar2

array([[ 0, 16,  6],
       [12, 45, 12],
       [ 7,  0, 45]])

In [74]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 3.        ]])

In [76]:
ar.sum()

37

In [77]:
ar.max()

9

In [78]:
ar.min()

0

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [80]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 2], dtype=int64))

In [81]:
type(np.where(ar>5))

tuple

In [82]:
np.count_nonzero(ar)

8

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [84]:
py_ar = [3, 51, 34, 2]

In [85]:
np_ar = np.array(py_ar)

In [86]:
import sys

In [87]:
sys.getsizeof(2) * len(py_ar)

112

In [88]:
np_ar.itemsize * np_ar.size

16

In [89]:
np_ar.tolist()

[3, 51, 34, 2]